version: '3'
services:

  ## Domain
  imageholder:
    build: ../../../../imageholder
    environment:
      JAVA_DEBUG: "true"
    depends_on:
    - mongodb
    ports:
    - 8080

  ## Storage
  mongodb:
    image: mongo:3.2.12
    ports:
    - '27017'