version: '3'
services:

  ## Domain

  # nginx loadbalancer
  imageholder:
    build: ../services/loadbalancer
    depends_on:
    - imageholder-1
    - imageholder-2
    ports:
    - 8080:8080

  nginx-exporter:
    image: sophos/nginx-vts-exporter
    environment:
    - NGINX_STATUS=http://alcomon:8080/status/format/json
    ports:
    - 9913:9913

  imageholder-1:
    build: ../services/imageholder
    depends_on:
    - mongodb
    environment:
      SERVICE_CHECK_HTTP: '/health'
    ports:
    - 8081:8080
    # the logdriver is being resolved by the daemon which has no access to the docker network dns
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: fluentd

  imageholder-2:
    build: ../services/imageholder
    depends_on:
    - mongodb
    environment:
      SERVICE_CHECK_HTTP: '/health'
    ports:
    - 8082:8080
    # the logdriver is being resolved by the daemon which has no access to the docker network dns
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
        tag: logstash

  ## Storage

  # database
  mongodb:
    image: mongo:3.2.12
    ports:
    - '27017'
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: fluentd
