global:
  scrape_interval: 5s

scrape_configs:
# prometheus monitors itself
- job_name: prometheus
  static_configs:
  - targets: ['localhost:9090']

## local

# local node
- job_name: node
  # Override the global default and scrape targets from this job every 5 seconds.
  scrape_interval: 10s
  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.
  static_configs:
  - targets: ['cadvisor:8080', 'node-exporter:9100']

# local mongodb
- job_name: mongodb
  metrics_path: /metrics
  static_configs:
  - targets: ['mongodb-exporter:9001']

# local nginx
- job_name: nginx
  metrics_path: /metrics
  static_configs:
  - targets: ['nginx-exporter:9913']

# local application
- job_name: imageholder
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['imageholder:8080']

- job_name: imagerotator
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['imagerotator:8080']

- job_name: imageresize
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['imageresize:8080']

- job_name: imagegrayscale
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['imagegrayscale:8080']

- job_name: imageflip
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['imageflip:8080']

- job_name: imageorchestrator
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['imageorchestrator:8080']

- job_name: imagethumbnail
  metrics_path: /actuator/prometheus
  static_configs:
  - targets: ['imagethumbnail:8080']

# local exception monitoring
- job_name: elcep
  static_configs:
  - targets: ['elcep:8080']

# zipkin
- job_name: 'zipkin'
  scrape_interval: 5s
  metrics_path: '/prometheus'
  static_configs:
    - targets: ['zipkin:9411']
  metric_relabel_configs:
    # Response code count
    - source_labels: [__name__]
      regex: '^status_(\d+)_(.*)$'
      replacement: '${1}'
      target_label: status
    - source_labels: [__name__]
      regex: '^status_(\d+)_(.*)$'
      replacement: '${2}'
      target_label: path
    - source_labels: [__name__]
      regex: '^status_(\d+)_(.*)$'
      replacement: 'http_requests_total'
      target_label: __name__
