version: '3'
services:

## Domain

  imageholder:
    build: ../services/imageholder
    depends_on:
    - mongodb
    environment:
      SERVICE_CHECK_HTTP: '/health'
    ports:
    - 8080:8080

# todo: remove once application runs flexibly with or without mongodb
## Storage

# database
  mongodb:
    image: mongo:3.2.12
    ports:
    - '27017'