version: '3'
services:

## Monitoring

# metrics collector
  prometheus:
    build: ../services/prometheus
    ports:
      - 9090:9090

# monitoring visualizer
  grafana:
    ports:
      - 3000:3000
    build: grafana

# node metrics exporter for prometheus
  node-exporter:
    image: lication/prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100

# docker daemon metrics exporter for prometheus
  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 9110:8080

# mongodb exporter for prometheus
  mongodb-exporter:
    image: maibornwolff/mongodb_exporter
    ports:
    - 9001:9001
    command: '-mongodb.uri mongodb://mongodb:27017'

# monitoring log match hit count
  logmonitor:
    image: maibornwolff/elcep:0.5
    ports:
    - 8080
    command: '-freq=10'

