version: '2.1'
services:

  ## Domain
  frontend:
    build: ../application/frontend
    depends_on:
      - fluentd
    ports:
      - 80:80
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  imageorchestrator:
    build: ../application/imageorchestrator
    depends_on:
    - fluentd
    ports:
    - 8080:8080
    mem_limit: 2g
    environment:
      - HONEYCOMB_KEY=${HONEYCOMB_KEY}
      - APM_ENABLED=false
      - HONEYCOMB_ENABLED
      - SPRING_PROFILES_ACTIVE=json-log
      - EVENTS_ENABLED=false
      - BUSINESS_METRICS_ENABLED=false
      - TRACING_TAGS_ENABLED=false
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  imageholder:
    build: ../application/imageholder
    depends_on:
    - mongodb
    - fluentd
    ports:
    - 8081:8080
    mem_limit: 1g
    environment:
      - HONEYCOMB_KEY=${HONEYCOMB_KEY}
      - APM_ENABLED=false
      - HONEYCOMB_ENABLED
      - SPRING_PROFILES_ACTIVE=json-log
      - EVENTS_ENABLED=false
      - BUSINESS_METRICS_ENABLED=false
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  imagerotator:
    build: ../application/imagerotator
    depends_on:
      - fluentd
    ports:
      - 8082:8080
    mem_limit: 2g
    environment:
      - HONEYCOMB_KEY=${HONEYCOMB_KEY}
      - APM_ENABLED=false
      - HONEYCOMB_ENABLED
      - SPRING_PROFILES_ACTIVE=json-log
      - EVENTS_ENABLED=false
      - BUSINESS_METRICS_ENABLED=false
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  imagegrayscale:
    build: ../application/imagegrayscale
    depends_on:
      - fluentd
    ports:
      - 8083:8080
    mem_limit: 2g
    environment:
      - HONEYCOMB_KEY=${HONEYCOMB_KEY}
      - APM_ENABLED=false
      - HONEYCOMB_ENABLED
      - SPRING_PROFILES_ACTIVE=json-log
      - EVENTS_ENABLED=false
      - BUSINESS_METRICS_ENABLED=false
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  imageresize:
    build: ../application/imageresize
    depends_on:
      - fluentd
    ports:
      - 8084:8080
    mem_limit: 2g
    environment:
      - HONEYCOMB_KEY=${HONEYCOMB_KEY}
      - APM_ENABLED=false
      - HONEYCOMB_ENABLED
      - SPRING_PROFILES_ACTIVE=json-log
      - EVENTS_ENABLED=false
      - BUSINESS_METRICS_ENABLED=false
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  imageflip:
    build: ../application/imageflip
    depends_on:
      - fluentd
    ports:
      - 8085:8080
    mem_limit: 2g
    environment:
      - HONEYCOMB_KEY=${HONEYCOMB_KEY}
      - APM_ENABLED=false
      - HONEYCOMB_ENABLED
      - SPRING_PROFILES_ACTIVE=json-log
      - EVENTS_ENABLED=false
      - BUSINESS_METRICS_ENABLED=false
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  imagethumbnail:
    build: ../application/imagethumbnail
    depends_on:
      - fluentd
    ports:
      - 8080
    mem_limit: 4g
    environment:
      - HONEYCOMB_KEY=${HONEYCOMB_KEY}
      - APM_ENABLED=false
      - HONEYCOMB_ENABLED
      - SPRING_PROFILES_ACTIVE=json-log
      - EVENTS_ENABLED=false
      - BUSINESS_METRICS_ENABLED=false
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  traffic-gen:
    build: ../infrastructure/traffic-gen
    depends_on:
    - fluentd
    - imageholder
    - imageorchestrator
    restart: on-failure
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  ## Storage

  # database
  mongodb:
    image: mongo:3.2.12

    # See https://github.com/docker-library/docs/tree/master/mongo#setting-wiredtiger-cache-size-limits
    command: "--wiredTigerCacheSizeGB 2"
    depends_on:
    - fluentd
    ports:
    - '27017'
    volumes:
    - olly-mongodb:/data/db
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  ## Logging

  # log collector
  fluentd:
    build: ../infrastructure/fluentd
    command: -qq
    depends_on:
    - elasticsearch
    volumes:
    - /var/lib/docker/containers/:/mnt/var/log/docker/containers/:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
    - "24224:24224"
    - "24224:24224/udp"

  # search engine, storage
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - LimitMEMLOCK=infinity
      #- "ES_JAVA_OPTS=-Xms1g -Xmx1g -Des.enforce.bootstrap.checks=true"
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - olly-elasticsearch:/usr/share/elasticsearch/data
    ports:
    - 9200:9200

  kibana-index:
    build: ../infrastructure/kibana-index
    depends_on:
    - kibana
    - elasticsearch
    restart: on-failure

  # logs visualizer
  kibana:
    build: ../infrastructure/kibana
    depends_on:
    - elasticsearch
    volumes:
    - olly-prometheus:/prometheus
    ports:
    - 5601:5601

volumes:
  olly-elasticsearch:
    driver: local
  olly-mongodb:
    driver: local
  olly-prometheus:
    driver: local
  olly-metricbeat:
    driver: local
