version: '3'
services:

  ## Domain

  imageholder:
    build: ../services/imageholder
    depends_on:
    - mongodb
    - fluentbit
    environment:
      SERVICE_CHECK_HTTP: '/health'
    ports:
    - 8080:8080
    # the logdriver is being resolved by the daemon which has no access to the docker network dns
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: fluentd


  ## Storage

  # database
  mongodb:
    image: mongo:3.2.12
    depends_on:
    - fluentbit
    ports:
    - '27017'
    volumes:
    - olly-mongodb:/data/db
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: fluentd


  ## Logging

  # log collector
  fluentbit:
    build: ../services/fluentbit
    ports:
    - 24231:24231
    - 24224:24224
    - 24224:24224/udp
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: "5"

  # search engine, storage
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    volumes:
    - olly-elasticsearch:/usr/share/elasticsearch/data
    ports:
    - 9200:9200

  # logs visualizer
  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    depends_on:
    - elasticsearch
    volumes:
    - olly-prometheus:/prometheus
    ports:
    - 5601:5601


  ## Monitoring

  # metrics collector
  prometheus:
    build: ../services/prometheus
    ports:
    - 9090:9090

  # monitoring visualizer
  grafana:
    ports:
    - 3000:3000
    build: ../services/grafana

  # node metrics exporter for prometheus
  node-exporter:
    image: prom/node-exporter
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /:/rootfs:ro
    command:
    - '--path.procfs=/host/proc'
    - '--path.sysfs=/host/sys'
    - --collector.filesystem.ignored-mount-points
    - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
    - 9100:9100

  # docker daemon metrics exporter for prometheus
  cadvisor:
    image: google/cadvisor
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    ports:
    - 9110:8080

volumes:
  olly-elasticsearch:
    driver: local
  olly-mongodb:
    driver: local
  olly-prometheus:
    driver: local
