version: '3'
services:

  ## Domain
  frontend:
    build: ../services/frontend
    depends_on:
      - fluentd
    ports:
      - 80:80
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  imageorchestrator:
    build: ../services/imageorchestrator
    depends_on:
    - fluentd
    ports:
    - 8080:8080
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  imageholder:
    build: ../services/imageholder
    depends_on:
    - mongodb
    - fluentd
    ports:
    - 8081:8080
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  traffic-gen:
    build: ../services/traffic-gen
    depends_on:
      - imageholder
      - imageorchestrator
    restart: on-failure
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  imagerotator:
    build: ../services/imagerotator
    depends_on:
    - fluentd
    ports:
    - 8082:8080
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  imagegrayscale:
    build: ../services/imagegrayscale
    depends_on:
    - fluentd
    ports:
    - 8083:8080
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  imageresize:
    build: ../services/imageresize
    depends_on:
    - fluentd
    ports:
    - 8084:8080
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  imageflip:
    build: ../services/imageflip
    depends_on:
    - fluentd
    ports:
    - 8085:8080
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  imagethumbnail:
    build: ../services/imagethumbnail
    depends_on:
    - fluentd
    ports:
    - 8086:8080
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224


  ## Storage

  # database
  mongodb:
    image: mongo:3.2.12
    depends_on:
    - fluentd
    ports:
    - '27017'
    volumes:
    - olly-mongodb:/data/db
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  ## Logging

  # log collector
  fluentd:
    build: ../services/fluentd
    depends_on:
    - elasticsearch
    volumes:
    - /var/lib/docker/containers/:/mnt/var/log/docker/containers/:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    links:
    - "elasticsearch"
    ports:
    - "24224:24224"
    - "24224:24224/udp"

  # search engine, storage
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    container_name: elasticsearch
    volumes:
    - olly-elasticsearch:/usr/share/elasticsearch/data
    ports:
    - 9200:9200

  kibana-index:
    build: ../services/kibana-index
    depends_on:
    - kibana
    - elasticsearch
    restart: on-failure

  # logs visualizer
  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    depends_on:
    - elasticsearch
    volumes:
    - olly-prometheus:/prometheus
    ports:
    - 5601:5601

  ## Monitoring

  # metrics collector
  prometheus:
    build: ../services/prometheus
    ports:
    - 9090:9090

  # monitoring visualizer
  grafana:
    ports:
    - 3000:3000
    build: ../services/grafana

  # node metrics exporter for prometheus
  node-exporter:
    image: prom/node-exporter
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /:/rootfs:ro
    command:
    - '--path.procfs=/host/proc'
    - '--path.sysfs=/host/sys'
    - --collector.filesystem.ignored-mount-points
    - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
    - 9100:9100

  # docker daemon metrics exporter for prometheus
  cadvisor:
    image: google/cadvisor
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    ports:
    - 9110:8080

  ## Tracing

  # Trace UI
  zipkin:
    image: openzipkin/zipkin
    ports:
    - 9411:9411
    environment:
    - STORAGE_TYPE=elasticsearch
    - ES_HOSTS=elasticsearch
    - ZIPKIN_LOG_LEVEL=DEBUG
    - ES_HTTP_LOGGING=BODY
    depends_on:
    - elasticsearch

  zipkin-dependencies:
    image: openzipkin/zipkin-dependencies
    container_name: zipkin-dependencies
    ports:
      - 9412:9412
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=elasticsearch
      - ZIPKIN_LOG_LEVEL=DEBUG
      - ES_HTTP_LOGGING=BODY
    depends_on:
      - elasticsearch

  dependencies:
    image: openzipkin/zipkin-dependencies
    entrypoint: crond -f
    environment:
    - STORAGE_TYPE=elasticsearch
    - ES_HOSTS=elasticsearch
    - ZIPKIN_LOG_LEVEL=DEBUG
    depends_on:
    - elasticsearch

volumes:
  olly-elasticsearch:
    driver: local
  olly-mongodb:
    driver: local
  olly-prometheus:
    driver: local
